[package]
name = "sechat-rs"
description = "A TUI based chat client for Nextcloud Talk"
readme = "README.md"
license-file = "LICENSE"
version = "0.1.0-beta"
edition = "2018"
categories = ["command-line-utilities"]
keywords = ["tui", "nextcloud", "nextcloud-talk"]
authors = ["tofu <sechat@tofuli.de>"]
documentation = "https://github.com/tofubert/sechat-rs"
repository = "https://github.com/tofubert/sechat-rs"
homepage = "https://github.com/tofubert/sechat-rs"
exclude = [
  "assets/*",
  ".github",
  "Makefile.toml",
  "CONTRIBUTING.md",
  "*.log",
  "tags",
]

[dev-dependencies]
mockall = { version = "0.13.1" }
mockall_derive = { version = "0.13.1"}

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jzon = "*"
base64 = "*"
toml = "*"
toml-example = "0.12.0"
ratatui = {version = "0.28", features = ["serde"] }
crossterm = "*"
tui-tree-widget = "0.22"
futures = "*"
chrono = "*"
num-traits = "*"
num-derive = "*"
log = "*"
log4rs = "1.3"
notify-rust = "4.11"
itertools = "*"
clap = { version = "4.5.23", features = ["derive"] }
strum = "0.26"
strum_macros = "0.26"
textwrap = "0.16.1"
etcetera = "0.8.0"
better-panic = "0.3.0"
color-eyre = "0.6.3"
human-panic = "2.0.2"
libc = "0.2.168"
strip-ansi-escapes = "0.2.0"
tracing = "0.1.41"
cfg-if = "1.0.0"
tui-textarea = "0.6.1"
async-trait = "0.1.83"
serde_with = "3.11.0"

[lints.clippy]
pedantic = "warn"
