coverage: # https://docs.codecov.com/docs/codecovyml-reference#coverage
  precision: 1 # e.g. 89.1%
  round: down
  range: 50..70 # https://docs.codecov.com/docs/coverage-configuration#section-range
  status: # https://docs.codecov.com/docs/commit-status
    project:
      default:
        threshold: 30% # While big refactors are happening this is ok.
    patch:
      default:
        threshold: 100%

comment: # https://docs.codecov.com/docs/pull-request-comments
  # make the comments less noisy
  require_changes: true

github_checks:
  annotations: false #Make commit readable again.

ignore:
  - "sechat-rs/src/main.rs"  #main is not testable.
