coverage: # https://docs.codecov.com/docs/codecovyml-reference#coverage
  precision: 1 # e.g. 89.1%
  round: down
  range: 85..100 # https://docs.codecov.com/docs/coverage-configuration#section-range
  status: # https://docs.codecov.com/docs/commit-status
    project:
      default:
        threshold: 10% # Avoid false negatives, while numbers are so low.
    patch:
      default:
        threshold: 2%

comment: # https://docs.codecov.com/docs/pull-request-comments
  # make the comments less noisy
  require_changes: true

github_checks:
  annotations: false #Make commit readable again.
