# configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
    "GPL-3.0",
]

[bans]
multiple-versions = "allow"
