name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

# ensure that the workflow is only triggered once per PR,  subsequent pushes to the PR will cancel
# and restart the workflow. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-make
      - uses: Swatinem/rust-cache@v2
      - run: cargo make lint-format

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-make
      - uses: Swatinem/rust-cache@v2
      - run: cargo make lint-typos

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-make
      - uses: Swatinem/rust-cache@v2
      - run: cargo make audit
      - run: cargo make deny


  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-make
      - uses: Swatinem/rust-cache@v2
      - run: cargo make clippy

  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-make
      - uses: Swatinem/rust-cache@v2
      - run: cargo make check
        env:
          RUST_BACKTRACE: full

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-make
      - uses: Swatinem/rust-cache@v2
      - run: cargo make coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-make
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo make build
      env:
          RUST_BACKTRACE: full
